# Generated by Django 2.1.5 on 2019-04-19 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Serive',
            new_name='Service',
        ),
    ]
